### ISSUE TITLE
Timestamp verifier tolerance for Alexa Skill Events

### ISSUE THREAD

**Issue by jadimmock** [amzn/alexa-skills-kit-java#141]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Alexa behaviour query
</code></pre>

## Expected Behavior
The documentation for skill events suggests that Alexa will attempt to redeliver skill events for [up to one hour if an acknowledgement is not received](https://developer.amazon.com/docs/smapi/skill-events-in-alexa-skills.html#delivery-of-events-to-the-skill).

The `SkillRequestTimestampVerifier` in V2.5.3 of the SDK enforces a maximum timestamp tolerance of 150 seconds, [as seen here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk-servlet-support/src/com/amazon/ask/servlet/verifiers/SkillRequestTimestampVerifier.java#L49).

Should we assume that redelivered events will include an updated timestamp on each redelivery attempt, or the timestamp from the original event? If the original event, can this maximum tolerance be relaxed? Our current implementation uses separate servlets for events and intent requests, allowing us to specify different tolerances for each.

**Comment by breedloj** [comment]
Hey James,

I was able to test this behavior and, in fact, the timestamp does not get updated with subsequent requests. That said, I only ever received 2 subsequent retry attempts, spaced one minute apart, so I am unsure if such requests could ever in fact continue for an hour. Just the same I am not opposed to changing the upper bound for the tolerance value since that would be a purely opt-in setting for end users.

**Comment by breedloj** [comment]
[This change](https://github.com/alexa/alexa-skills-kit-sdk-for-java/commit/da0358622c7c418132be943112e6b8ec54075630) bumps the maximum tolerance and will be included in the next release (though you can start using it now by compiling from source).
