### ISSUE TITLE
Cannot make dynamic entities work

### ISSUE THREAD

**Issue by kalina-l** [amzn/alexa-skills-kit-java#214]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: help :)
</code></pre>

## Expected Behavior

Hi, I have a problem with dynamic entities. I have an Intent with a Slot which should be populated with dynamic values on the start of the app.
I placed my DynamicEntitiesDirective code in the LaunchRequestHandler and want to use the populated slot withing a different Handler. Unluckily it does not work.

## Current Behavior

This is how I create my dynamic entities:
```
public DynamicEntitiesDirective generateEventsKeywords() {
        List<Entity> entities = new ArrayList<>();
        List<Event> events = eventService.getCachedEvents();
        LOG.info("Cached events: " + events.size());
        Set<String> keywords = new HashSet<>();
        for (Event event : events) {
            String[] words = event.getTitle().split(" ");
            for (String word : words) {
                keywords.add(word);
            }
        }
        for (String keyword : keywords) {
            Entity entity = Entity.builder()
                    .withId(keyword)
                    .withName(EntityValueAndSynonyms.builder()
                            .withValue(keyword)
                            .build())
                    .build();
            entities.add(entity);
        }
        LOG.info("Entities to save: " + entities);
        DynamicEntitiesDirective replaceEntityDirective = DynamicEntitiesDirective
                .builder()
                .addTypesItem(EntityListItem.builder()
                        .withName("TerminDynamic")
                        .withValues(entities)
                        .build())
                .withUpdateBehavior(UpdateBehavior.REPLACE)
                .build();
        return replaceEntityDirective;
    }
```

As I said before I register this Directive in the LaunchRequestHandler with the  
 .addDirective(generateEventsKeywords()) and then expect to see updated resolutions when I get the slots in the other Handler, but all I get is:

```
class Intent {
    name: EventsDate
    slots: {TerminDynamic=class Slot {
        name: TerminDynamic
        value: null
        confirmationStatus: NONE
        resolutions: null
    }}
    confirmationStatus: NONE
}
```

The resolutions are empty...  Do you have an idea why it doesn't work? Have I done somethind wrong? Would appreciate some help!

## Your Environment

* ASK Java SDK version used: 2.20.1
* Operating System and version: Windows 10

**Comment by kalina-l** [comment]
Still having this problem, does anyone has an idea whats wrong?

**Comment by teddy-owen** [comment]
It seems that Amazon has not provided the info and/or capabilities for this to work, after lots of investigation. 
the issue is that Dynamic entities requires you to first create a catalog for the target slot. Docs state:
"To use dynamic entities, ensure that your skill has a static catalog with defined slot types and slot names."
Then, when you actually try to create a catalog, you must choose a type from the following list: "AMAZON.MusicAlbum", "AMAZON.MusicGroup", "AMAZON.Genre", 
"AMAZON.MusicPlaylist", "AMAZON.MusicRecording", "AMAZON.BroadcastChannel". If your slot is not music related, youre out of luck.
So maybe, you think you can just pick an arbitrary type and go from there, but then you find that they have restrictions on what 
the catagory entities can look like which of course will all be music specific.
My experience with Alexa development has been so bad, that Im considering moving only to the Google home. This "Dynamic entities" feature is such a common use case, 
that I cannot believe how poorly documented and difficult it is. My app contains a simple, dynamic list of items for each of my users. They can edit that
list. Then, I want alexa to ask them to pick one of the items on their list. So of course, the slot value (list_item) expects them to say one of those items
and then match it to the correct/closest one. Unfortuneatly this simple and common task has proven to be nearly impossible. Id appreciate any guidance
and I hope Amazon publishes MUCH clearer documentation for the steps of how to achieve this. 

Sources:
- Need catalog to use Dynamic Entities: https://developer.amazon.com/en-US/docs/alexa/custom-skills/use-dynamic-entities-for-customized-interactions.html#update-the-list-of-entities-with-the-dialogupdatedynamicentities-directive
- Create catalog via API: https://developer.amazon.com/en-US/docs/alexa/smapi/catalog-content-upload.html
- Create catalog via CLI: https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#create-catalog-subcommand
- Catalog types: https://developer.amazon.com/en-US/docs/alexa/music-skills/catalog-reference.html#catalog-type

**Comment by Shreyas-vgr** [comment]
Thanks for reporting this issue. Tracking this issue at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/598
