### ISSUE TITLE
Token is not available in request object

### ISSUE THREAD

**Issue by Kailash2509** [amzn/alexa-skills-kit-java#223]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

"getToken()" method is not available in request object : - 
For AudioPlayer.PlaybackFailed request and I believe other request also, as per the page ("https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html")
the request object should contain token, but when I try to get 'token' on the input handler request (input.getRequestEnvelope().getRequest()) , I don't see "getToken" method on request object, I see only getLocale(), getRequestId(), getTimeStamp() and getType(). But there should be one getToken() method also as per above link 

## Expected Behavior
 getToken() method should be available.

## Current Behavior
 getToken() method is not present.

## Steps to Reproduce (for bugs)
```
In the ecliplse Id on the input handler method try below : - 

public Optional<Response> handle(HandlerInput input) {
		logger.error("inside System.PlaybackFailed  handler");
		logger.error(input.getRequestEnvelope().getRequest().toString());
		logger.error(input.getContext().toString());
		logger.error(input.getRequestEnvelope().getRequest().getRequestId());
		input.getRequestEnvelope().getRequest().g   ( give CTRL + SPACE here)
```

## Possible Solution
 
```

## Context
 
## Your Environment
<!--- Include as many relevant details about the environment where the bug was discovered -->
	<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk</artifactId>
			<version>2.21.0</version>

WINDOWS 

## Java Info
<!--- For Java issues, please provide the following -->
JAVA 8
![Capture](https://user-images.githubusercontent.com/40264868/63649205-6a8a2a80-c758-11e9-8bbe-11cb76c93aa6.PNG)

**Comment by breedloj** [comment]
Hey, thanks for reaching out. Because you are using the generic low-level RequestHandler which is not request specific, you will need to check the type of the incoming request and cast accordingly (in this case, to https://github.com/alexa/alexa-apis-for-java/blob/master/ask-sdk-model/src/com/amazon/ask/model/interfaces/audioplayer/PlaybackFailedRequest.java) since the generic Request class does not contain any type-specific properties. Alternately, you could use a type specific request handler (in this case, https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk-core/src/com/amazon/ask/dispatcher/request/handler/impl/PlaybackFailedRequestHandler.java) to avoid having to make the cast or check the request type.

Documentation about all of this is at [this location](https://developer.amazon.com/docs/alexa-skills-kit-sdk-for-java/handle-requests.html#request-handlers). Let me know if you have any other questions!

**Comment by Kailash2509** [comment]
Thanks @breedloj , it worked , Thanks :)
